/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f6ff",
        "primary-fixed": "#dbeafe",
        "primary-fixed-dim": "#bfdbfe",
        "on-tertiary-fixed-variant": "#930013",
        "on-secondary": "#ffffff",
        "primary": "#1d4ed8",
        "surface-container-high": "#e0eaff",
        "on-tertiary-fixed": "#410004",
        "on-secondary-fixed-variant": "#005236",
        "outline-variant": "#cbd5e1",
        "inverse-surface": "#1e293b",
        "on-surface": "#0f172a",
        "primary-container": "#2563eb",
        "tertiary": "#870011",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary-container": "#ffbfba",
        "surface-container": "#eff6ff",
        "on-primary-container": "#eff6ff",
        "outline": "#64748b",
        "on-secondary-fixed": "#002113",
        "surface-dim": "#e2e8f0",
        "on-primary-fixed": "#1e3a8a",
        "surface-tint": "#2563eb",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#6ffbbe",
        "background": "#f8fafc",
        "surface-variant": "#e2e8f0",
        "inverse-primary": "#93c5fd",
        "surface-container-highest": "#cbd5e1",
        "surface-bright": "#f8fafc",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary": "#006c49",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#334155",
        "secondary-container": "#6cf8bb",
        "inverse-on-surface": "#f1f5f9",
        "on-primary-fixed-variant": "#1e40af",
        "on-error-container": "#93000a",
        "tertiary-container": "#b0111e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface": "#f9f9ff",
        "on-background": "#151c27",
        "on-secondary-container": "#00714d",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#4edea3"
      },
      spacing: {
        "container-margin": "24px",
        "stack-lg": "32px",
        "section-gap": "64px",
        "base": "8px",
        "stack-sm": "8px",
        "gutter": "16px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "voting-number": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "voting-number": ["20px", { "lineHeight": "24px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

